# Generated by Django 5.0.2 on 2024-03-10 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_adminmaster_id_alter_collegemaster_college_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMaster',
            fields=[
                ('stu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('enrollment_no', models.IntegerField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('hod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hodmaster')),
            ],
            options={
                'db_table': 'StudentMaster',
            },
        ),
        migrations.CreateModel(
            name='GrievanceMaster',
            fields=[
                ('grievanceId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Enrollment', models.IntegerField(max_length=50, null=True)),
                ('semester', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('message', models.CharField(max_length=200)),
                ('collage_Fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.collegemaster')),
                ('department_Fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.departmentmaster')),
                ('directer_Fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.directormaster')),
                ('hod_Fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.hodmaster')),
                ('trust_Fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.trustmaster')),
                ('university_Fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.universitymaster')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.studentmaster')),
            ],
            options={
                'db_table': 'GrievanceMaster',
            },
        ),
    ]
