# Generated by Django 5.0.2 on 2024-03-10 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_studentmaster_grievancemaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmaster',
            name='hod_id',
            field=models.ForeignKey(db_column='hod_id', on_delete=django.db.models.deletion.CASCADE, to='app.hodmaster'),
        ),
    ]
