# Generated by Django 5.0.2 on 2024-03-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_grievancemaster_enrollment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directormaster',
            name='img',
        ),
    ]
