# Generated by Django 4.2.5 on 2024-04-07 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_hodmaster_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universitymaster',
            name='logo',
        ),
        migrations.CreateModel(
            name='SolveGrievance',
            fields=[
                ('solvGrievanceId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=150, null=True)),
                ('Statement', models.CharField(max_length=300)),
                ('solver_role', models.CharField(max_length=30)),
                ('solver_Email', models.CharField(max_length=50)),
                ('GrievanceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grievancemaster')),
                ('studentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.studentmaster')),
            ],
        ),
    ]
