# Generated by Django 4.2.5 on 2024-04-07 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_universitymaster_logo_solvegrievance'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='solvegrievance',
            table='SolveGrievance',
        ),
    ]
