# Generated by Django 4.2.5 on 2024-04-07 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_solvegrievance_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solvegrievance',
            name='Statement',
        ),
        migrations.AddField(
            model_name='solvegrievance',
            name='solution',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='solvegrievance',
            name='solver_name',
            field=models.CharField(db_column='solver_name', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solvegrievance',
            name='solver_Email',
            field=models.CharField(db_column='solver_Email', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solvegrievance',
            name='solver_role',
            field=models.CharField(db_column='solver_role', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='solvegrievance',
            name='studentId',
            field=models.ForeignKey(db_column='student', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.studentmaster'),
        ),
    ]
