# Generated by Django 4.2.5 on 2024-04-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_solvegrievance_statement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievancemaster',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='solvegrievance',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studentmaster',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
