# Generated by Django 4.2.5 on 2024-04-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_grievancemaster_create_at_solvegrievance_create_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('barcode_data', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
