# Generated by Django 4.2.5 on 2024-04-09 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
