# Generated by Django 4.2.5 on 2024-04-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_studentmaster_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmaster',
            name='barcode',
            field=models.ImageField(blank=True, height_field='50px', null=True, upload_to='StudentImg/', width_field='50px'),
        ),
    ]
