# Generated by Django 4.2.5 on 2024-04-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_studentmaster_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmaster',
            name='enrollment_no',
            field=models.IntegerField(),
        ),
    ]
